export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const UPDATE_USER = "UPDATE_USER";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const GET_NUMBER_CART = "GET_NUMBER_CART";
export const ADD_CART = "ADD_CART";
export const UPDATE_CART = "UPDATE_CART";
export const DELETE_CART = "DELETE_CART";
export const DELETE_ALL_CART = "DELETE_ALL_CART";



export const ADD_ORDERDETAILS = "ADD_ORDERDETAILS";
export const REMOVE_ORDERDETAILS = "REMOVE_ORDERDETAILS";
export const GETALL_ORDERDETAILS_CART = "GETALL_ORDERDETAILS_CART";
export const INCREASE_QUANTITY_ORDERDETAIL = "INCREASE_QUANTITY_ORDERDETAIL";
export const UPDATE_ORDERDETAILS = "UPDATE_ORDERDETAILS";
export const COUNT_ORDERDETAIL_PENDING = "COUNT_ORDERDETAIL_PENDING";